### ISSUE TITLE
Trash folder problem (In experimental-12.2)

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Filer#38] opened 2021-02-22 03:40 UTC
1. When the files on the desktop are directly moved to the trash can, the moving menu will be displayed, Not moved directly to the trash.
![image](https://user-images.githubusercontent.com/44593430/108652641-9af28680-74ff-11eb-83dc-eef4d2199714.png)

2. An error occurs when moving files from the desktop to the trash.
![image](https://user-images.githubusercontent.com/44593430/108653200-d17cd100-7500-11eb-9c5d-9d90151ed819.png)

3. When in the file manager will move files to the trash, but not working.
![image](https://user-images.githubusercontent.com/44593430/108653828-6fbd6680-7502-11eb-8257-04f71eca3206.png)

 4.  In the file manager or the desktop, Move the files to the Dock trash, Is not working.
 5.  Click the Dock trash, Is not working
![image](https://user-images.githubusercontent.com/44593430/108654430-a051d000-7503-11eb-8a24-bb292d8117f5.png)

6. After selecting "Move to Trash" from the right-click menu of the file, there is no original file in the trash can.
![image](https://user-images.githubusercontent.com/44593430/108654376-82846b00-7503-11eb-977e-5ac1c4f31b55.png)

**Comment by probonopd** [comment] 2021-06-28 17:57
Duplicate of https://github.com/helloSystem/Filer/issues/11, closing here.

**Closed by probonopd** 2021-06-28 17:57 UTC
Labels: bug

**Comment by probonopd** [comment] 2021-06-28 22:23
There is now Edit -> Empty Trash in the menu.
https://github.com/helloSystem/Filer/commit/287144717041f28f05a1ec42473f03af0a3dc745
