### ISSUE TITLE
[maybe devel/gvfs] Volume icons persist after volumes are unmounted

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Filer#65] opened 2021-03-28 21:49 UTC
Partly following on from https://github.com/helloSystem/Filer/issues/9

![2021-03-28 22:27:26](https://user-images.githubusercontent.com/192271/112769184-99910e00-9017-11eb-8d04-583c52675e95.png)

![2021-03-28 22:28:58](https://user-images.githubusercontent.com/192271/112769212-ba596380-9017-11eb-9972-4fd3cfb74192.png)

**Comment by probonopd** [comment] 2021-03-29 23:50
I cannot reproduce this using helloSystem build: 0E57 for commit: 80061bf on real hardware.

**Comment by grahamperrin** [comment] 2021-03-30 01:22
Installed, or live boot?

**Comment by probonopd** [comment] 2021-03-30 08:16
I tested on Live ISO.

**Comment by grahamperrin** [comment] 2021-03-30 17:11
Why did you assume that it's a VirtualBox issue without testing an installation?

**Comment by probonopd** [comment] 2021-03-30 20:24
Looking at your screenshots, VitualBox is in use. I have started to mark all issues that involve VirtualBox with the `[VirtualBox]` prefix until the issue has been reproduced on real hardware. Also, looking at your screenshots, the installed system seems to be modified and/or upgraded? For testing, it would be most helpful to test with "factory fresh" builds :)

**Comment by probonopd** [comment] 2021-10-05 17:42
Volume icons are correctly removed after volumes are unmounted no helloSystem 0.6.0.

Please comment here if the problem persists.

**Comment by grahamperrin** [comment] 2021-10-16 18:50
> Please comment here if the problem persists.

https://github.com/helloSystem/hello/issues/161#issuecomment-944977032

>  icon on the desktop, showing the empty(!) DVD drive.

@probonopd what exactly happens after you double-click the icon? 

Given your experience with real hardware, it might be appropriate to _remove_ **[VirtualBox]** from the subject line.

**Comment by probonopd** [comment] 2021-10-16 19:29
It would be interesting to know how a freshly installed helloSystem 0.6.0 (installed to hard disk) performs.
Then do just the FrreeBSD update, reboot, see if the problem appears.
Then also do the packages update, reboot, see if rhe problem appears.

**Comment by probonopd** [comment] 2021-10-16 19:34
Why a thumbs down?

**Comment by probonopd** [comment] 2021-10-16 19:36
Without a disc inserted:

```
FreeBSD% gio info 'computer:///HL-DT-ST DVD+-RW GH50N.drive' 
Anzeigename: HL-DT-ST DVD+-RW GH50N
Name: HL-DT-ST DVD+-RW GH50N.drive
Typ: mountable
Adresse: computer:///HL-DT-ST%20DVD+-RW%20GH50N.drive
Attribute:
  standard::type: 6
  standard::name: HL-DT-ST DVD+-RW GH50N.drive
  standard::display-name: HL-DT-ST DVD+-RW GH50N
  standard::icon: drive-optical, drive, drive-optical-symbolic, drive-symbolic
  standard::sort-order: -3
  standard::symbolic-icon: drive-optical-symbolic, drive-symbolic, drive-optical, drive
  id::filesystem: computer:
  access::can-write: FALSE
  access::can-delete: FALSE
  access::can-trash: FALSE
  access::can-rename: FALSE
  mountable::can-mount: FALSE
  mountable::can-unmount: FALSE
  mountable::can-eject: TRUE
  mountable::unix-device-file: /dev/cd0
  mountable::can-start: FALSE
  mountable::can-start-degraded: FALSE
  mountable::can-stop: FALSE
  mountable::start-stop-type: 1
  mountable::can-poll: FALSE
  mountable::is-media-check-automatic: TRUE
```

**Comment by probonopd** [comment] 2021-10-16 19:45
I _think_ I never saw `computer:///*.drive` entries before running the update. If that is the case then it should hopefully be relatively easy to filter them away in Filer. Or maybe there is a config setting _somewhere_ (in gio? gvfs? GnomeVFS? UDisks? BSDDisks` to switch the `*.drive` stuff off again.

Will investigate.

**Comment by probonopd** [comment] 2021-10-16 20:30
libfm cannot be it, as we are using a privately bundled one.

**Comment by probonopd** [comment] 2021-10-16 20:44
I have the gut feeling that this has to do with it:

```
FreeBSD% pkg which /usr/local/libexec/gvfsd-computer

/usr/local/libexec/gvfsd-computer was installed by package gvfs-1.46.2
```

**Comment by grahamperrin** [comment] 2021-10-17 03:17
> gone

Similarly, 

https://github.com/helloSystem/Filer/issues/65#issuecomment-944993766

The `cd0` icon, and Filer's ghostly view of a file system that was unmounted prior to opening of the window, seem to be symptoms of a bug that is transient (that does not survive a restart of the OS): 

![image](https://user-images.githubusercontent.com/192271/137609265-6be62ecb-383f-4aff-b244-9420b1a7710f.png)

https://github.com/helloSystem/Filer/issues/65#issuecomment-934625047

> Volume icons are correctly removed after volumes are unmounted …

Please: was there a related commit, or was that simply an observation of behaviour at the time?

**Comment by probonopd** [comment] 2021-10-17 09:13
> Volume icons are correctly removed after volumes are unmounted on helloSystem 0.6.0.

That was simply an observation by looking at what the Live ISO does.

**Comment by grahamperrin** [comment] 2021-10-17 16:28
> 10. reloading the desktop reorders the three items, the two error-related items remain non-openable (neither a window, nor an error): …

11. `shutdown -p now`
12. started the virtual machine
13. there remained desktop icons for the virtual hard disk and empty virtual optical drive, with errors when opened
14. inserted `hello-0.6.0_0F54-FreeBSD-12.2-amd64.iso` in the optical drive
15. the desktop icon for the optical drive remained non-usable, reloading the desktop did not resolve the issue
16. `geom disk list` shows `Mediasize: 0 (0B)` for `cd0`.

**Comment by probonopd** [comment] 2021-10-17 16:33
I suspect that the gvfs package is causing this. Actually this may be the behavior _wanted_ by the gvfs people (but not by us). So _maybe_ the earlier package `gvfs-1.46.2` had a bug that prevented those nasty entries from being created, lucky for us. If you are brave, try downgrading to `gvfs-1.46.2` and see if the issue goes away.

**Comment by probonopd** [comment] 2021-10-18 18:04
In Filer, we have

```
computerFolder_ = fm_folder_from_path(fm_path_new_for_uri("computer://"));
```

Apparently this loads _everything_ from `computer://`. I didn't find a way to filter out `.drive` entries yet. (We _only_ want `.mount` entries.)

**Comment by probonopd** [comment] 2021-11-17 19:55
Deleting `/usr/local/share/dbus-1/services/org.gtk.vfs.UDisks2VolumeMonitor.service` fixed this issue, so closing here.

That a package update in FreeBSD will write it there again is [another issue](https://github.com/helloSystem/ISO/issues/312).

**Closed by probonopd** 2021-11-17 19:55 UTC
